### ISSUE TITLE
Add speed control

### ISSUE THREAD

**Issue by nicodelpiano** [nicodelpiano/sorting-algorithms-visualizer#15]
Would be nice to add a text input field to control the speed of the algorithm.

The default speed is set [here](https://github.com/nicodelpiano/sorting-algorithms-visualizer/blob/7871ed386544e850d6d1cd204793da2087fb9ca4/app.js#L10) and the drawing function accepts the speed as a parameter [here](https://github.com/nicodelpiano/sorting-algorithms-visualizer/blob/7871ed386544e850d6d1cd204793da2087fb9ca4/app.js#L51).

The front-end doesn't need to be super fancy.

**Comment by jpacsai** [comment]
I would like to work on this issue please :)

**Comment by nicodelpiano** [comment]
Sounds good @jpacsai, feel free to give it a shot!
