### ISSUE TITLE
Avoid overlapping algorithms

### ISSUE THREAD

**Issue by nicodelpiano** [nicodelpiano/sorting-algorithms-visualizer#2]
Currently, if you click on an algorithm and then click on another one before the first one finishes, the rendering overlaps and makes it look a bit weird.

One solution for this could be to avoid executing new algorithms if one is currently running.

This task is to solve this problem, and if you find any other solutions or ideas feel free to give them a go!

**Comment by giordanna** [comment]
hi there, i would like to work on this

**Comment by nicodelpiano** [comment]
Hi @giordanna! Feel free to start working on this, thank you 👍 !

**Comment by nicodelpiano** [comment]
Closed via #7 .
