### ISSUE TITLE
Display number of steps

### ISSUE THREAD

**Issue by nicodelpiano** [nicodelpiano/sorting-algorithms-visualizer#9]
Display the number of steps somewhere below the canvas.

It could be just something simple like `currentStepNumber/totalSteps`.

**Comment by CoryWritesCode** [comment]
I could try this!

**Comment by nicodelpiano** [comment]
@CoryWritesCode sounds good, thanks! 💯

**Comment by misaelgosantos** [comment]
how it´s work?

**Comment by nicodelpiano** [comment]
Closed via #12.
